name: Generate Plugin Archive
on:
  workflow_dispatch

jobs:
  generate-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generating zip
        uses: rudlinkon/action-wordpress-build-zip@master
        with:
          retention-days: 7 # Optional; defaults to 3
          npm-run-build: true # Optional; defaults to false
          node-version: 14 # Optional; defaults to 16