# Deploy to WP.org
name: Deploy to WordPress.org

on:
  push:
    tags:
    - "*"
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      # node version
      - uses: actions/setup-node@v2
        with:
            node-version: '20'
      - name: Running NPM Install & Build For Gutenberg
        run: |
          npm install --silent && npm run build
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}